### ISSUE TITLE
Funds missing

### ISSUE THREAD

**Issue by Alex71btc** [BlueWallet/rn-ldk#50]
Here is what happened: 

I was setting up a LDK lightning Wallet with setting up a channel from funds of some of my watch only btc wallets.

It was working fine in the beginning I could transact,  but [today](calendar:T5:today) the channel disappeared and wallet shows 0 balance. and then a message showed up under 'mange funds' to claim like 58 Euros of Sats but if I try to claim it let me choose wallet but then nothing happens any further. 

How do I receive my funds now please? 

Currently connected to my own node...

Otherwise love BW!

Kind regards a fellow bitcoiner

**Comment by Funman2** [comment]
Solved by connecting to BW electrum backend. 
Funds showed up after claiming again. 
That did not work when connected to electrs from umbrel node....
