### ISSUE TITLE
Example App crashes when connecting to my local Umbrel node

### ISSUE THREAD

**Issue by LAMike310** [BlueWallet/rn-ldk#7]
Hello,

I tried changing the parameters on line 51 of `App.tsx` to include my local node info. 

```
RnLdk.connectPeer('03af20bea87280ba29c4a6c1dac20b577a3b2e137bf33235e08ee3c90c3747a997', 'sf7f5ca3vctibwqg4otsyo7qb2gwa7zgebqybi57uvengp5obthbx2ad.onion', 9735).then(console.warn);
```

The app automatically closes when I tap the "connect peer" link. 

What could be causing this, is it because I have a Tor address? 

Looking forward to learning more! 

Thanks

**Comment by LAMike310** [comment]
Update: It seems like I can connect to another non-Tor node like Zebedee:

```RnLdk.connectPeer('0251fff168b58b74e9b476af5a515b91fe0540a3681bc97fbb65379a807aea5f66', '3.227.49.48', 9735).then(console.warn);```

**Comment by marcosrdz** [comment]
LDK does not support Tor at the moment.
