### ISSUE TITLE
Running Example app crashes on `RnLdk.openChannelStep2`

### ISSUE THREAD

**Issue by LAMike310** [BlueWallet/rn-ldk#8]
I created a random entropy seed, hit the `start & `openChannelStep1` link. 

I then sent a small payment to the address:

https://live.blockcypher.com/btc/tx/cbd20a902d5cdb16712f06ff1237e6c921ea4e3bc46a56c98ce6612fc5e8a2ca/

I tried to manually enter the TXID in the `openChannelStep2` link like this:

```
<Button
        onPress={() => {
          // if (!text) return;
          RnLdk.openChannelStep2('cbd20a902d5cdb16712f06ff1237e6c921ea4e3bc46a56c98ce6612fc5e8a2ca').then(console.warn);
        }}
        title="openChannelStep2"
        color="#841584"
      />
```

But the app crashes whenever I try doing that. I think something is wrong with the way I'm constructing the transaction.

Is sending BTC to the Step 1 address enough? Is there an easier way to do this with bitcoin-cli?

Thanks!

**Comment by Overtorment** [comment]
you must NOT send funds to this address yourself, such funds are probably lost (or hard to recover, which would require cooperation of the remote node).
you must construct transaction that pays to this address specified amount, and provide to step2 txhex of the transaction. LDK will verify that transaction is okay, and will broadcast it if all is good

**Comment by LAMike310** [comment]
Ok that's fine, I made a small test payment of 500 Satoshi, I'll consider it an offering to the Bear market lol

Please check out this video and let me know if I'm doing anything wrong with my process. In this version, I didn't broadcast the transaction, but the same result happened when I entered the TXID. I also entered the text below, which I think is the TX Hex, and the app crashed as well. Now I'm having trouble creating an address with Step 1, with the error being: 

`timeout waiting for FundingGenerationReady event`

I'm going to try to get the repo going from scratch to see if I can get Step 1 working again. I also started downloading Bitcoin Core on my desktop instead of an Umbrel, so maybe using the bitcoin-cli would make it easier than the GUI. 

https://youtu.be/Idchf2Jn_TI

**Comment by LAMike310** [comment]
Reading further into the logs I see the error message:

`size of 0.00005 BTC is below min chan size of 0.0002 BTC`

Look like I'll need to increase my channel size to at least 20,000 Satoshi

**Comment by LAMike310** [comment]
I was able to broadcast a transaction from Step 2 after I increased the channel size to 20,000 Satoshi and entered the final TX Hex from Sparrow. 

Now I'll wait for the TX to confirm and see if I can send some test payments around

**Comment by Overtorment** [comment]
i looked at your video, and 

1) yes, you're using txid which is wrong. you need txhex. looks like its the one below (in sparrow interface)
2) its better to not edit source code while rn-ldk example runs - it might screw up internal state of js wrapper class. copy txhex and paste it in input  field  on the simulator

PS. step1 might timeout because remote end didn't respond to your attempt to open a channel this might happen when you initialized way too many channels with this peer and didn't finalize any of them. at this point its easier to use some other peer, and try to create a channel with him

**Comment by LAMike310** [comment]
Ok thanks I will try to run on the clearnet node I'm setting up now on my desktop. Was able to connect to the original node in the video and send a small test payment successfully.
